### ISSUE TITLE
How to access stuff in nvim aside from aniseed.nvim

### ISSUE THREAD

**Issue by tami5** [Olical/aniseed#10]
Hay, I'm trying to configure lsp using [nvim-lsp](https://github.com/neovim/nvim-lspconfig) . So after a while I managed to know how to import a plugin I installed with

```fnl
(module dotfiles.module.lsp 
  {require 
   {nvim aniseed.nvim 
    nvim_lsp "nvim_lsp"
    }})
```

Now, I'm trying to access `vim.lsp.get_log_path()`. 

Thanks,

**Comment by tami5** [comment]
:D Ohh sorry, managed to access it via "vim.lsp" . Cool its easy, I wish if there a wiki to make things easier. I'll try to write a how to lines for challenges I face. Thanks.

**Comment by psunanand** [comment]
@tami5 Hi Tami, sorry for re-openning this, but I was hoping you could help me out on this one. I was trying to set up the built-in nvim lsp with aniseed and now I'm having a hard time trying to translate this into fennel.

```lua
local on_attach_vim = function (client)
  require'completion'.on_attach (client)
end

require 'nvim_lsp'.setup (on_attach=on_attach_vim)
```
Also, there is no better way to do the mapping than this right ?

```vim
nnoremap gd          <cmd>lua vim.lsp.buf.definition()<CR>
```

```fennel
(nvim.set_keymap :n :gd "<cmd>lua vim.lsp.buf.definition()<CR>" {:noremap true})
```

**Comment by tami5** [comment]
Hey @psunanand , sure no problem. 

```lua
local x = function () end 
-- which is the same as
local function x () end
``` 
translate to fennel like this `(defn- x [])`. 

for `require'module.y'.function`, I'd suggest first requiring like that, however, you can just do (def my (require my))`:
```
  (module x 
    {require {core aniseed.core 
              my "module.y" }})
```

For your particular case try this: _not tested!_ 

```
(defn- on_attach_vim [client]
  (let [completion (require "completion")]
    (completion.on_attach client))

(defn setup-lsp [client]
  (let [lsp (require "nvim_lsp")
        on_attach (on_attach_vim client)]
    (lsp.setup {:on_attach on_attach_vim} )))

```

**Comment by tami5** [comment]
For mappings @psunanand, you may define a wrapper function to make your life easier

```
(defn bind [mode map action & opts]
  (let [opts (if (str.blank? opts) {:noremap true :silent false})]
   ;; maybe you need require statement
      (nvim.set_keymap mode map action opts)
    ))

```

**Comment by psunanand** [comment]
@tami5 Thanks so much for your inputs, especially your reference link. There is one thing that I don't understand about his code which is 

```fennel
(each [server config (pairs lsp.configs)]
  (-> (lsp.get-config config)
      ((. nvim-lsp server "setup"))))
```

I was trying to look for the reference of '.' but can't find any. I only know that '..' means to concat

**Comment by Olical** [comment]
Thank you so much @tami5 for helping out here! Finally I can help a little :D `.` is [table lookup](https://fennel-lang.org/reference#table-lookup).

**Comment by tami5** [comment]
@Olical 😄 For sure, hope I could do more😎
