### ISSUE TITLE
Illegal characters in `'iskeyword'` option

### ISSUE THREAD

**Issue by monkoose** [Olical/aniseed#105]
I guess 38 that is `&` and 126 that is `~` should be removed from `'iskeyword'` option because they are reserved and do not allowed as keyword name.
Or am I miss something?
https://github.com/Olical/aniseed/blob/bd79727af8a21037222a08ec9bcaf1c85488aaa4/ftplugin/fennel.vim#L14

**Comment by Olical** [comment]
I think you're right, it seems like they were disallowed at some point but were allowed in the past: https://fennel-lang.org/changelog

So this is just outdated.
