### ISSUE TITLE
Can't set auto-pairs to be empty table

### ISSUE THREAD

**Issue by Liverm0r** [Olical/aniseed#108]
Don't sure if the question is appropriate here, but may be you will be able to answer it immediately:

In your dotfiles you have `dotfilnves.plugin.auto-pairs` where you use `nvim.g.AutoPairs` like this:
```fennel
(defn init []
  (let [auto-pairs nvim.g.AutoPairs]
    (tset auto-pairs "'" nil)
    (tset auto-pairs "`" nil)
    (set nvim.b.AutoPairs auto-pairs)))
```

I tried to use jusn an empty table (as it works without this plugin in lisps) with code
```fennel
(defn init []
  (let [d {}] 
    (set nvim.b.AutoPairs d)))
```

But I get the error:
```vim
Error detected while processing function AutoPairsTryInit[62]..AutoPairsInit:  
line   22:
E715: Dictionary required
E1098: String, List or Blob required
```
On line 22 of autoPairs there is this line
<img width="483" alt="image" src="https://user-images.githubusercontent.com/14236531/161937240-dd90d523-65a1-4213-ab15-084e4fd7b435.png">
which doesn't tell me anything.

And before I have this line in vimrc and it worked just fine:
`au Filetype clojure let b:AutoPairs={}`

**Comment by Olical** [comment]
Ah yeah, `vim.empty_dict()` looks like what you want. I just searched for "neovim lua pass empty dict" for context.
