### ISSUE TITLE
Add `:Fnlfile`

### ISSUE THREAD

**Issue by bandithedoge** [Olical/aniseed#111]
[hotpot.nvim](https://github.com/rktjmp/hotpot.nvim) has a [`:Fnlfile`](https://github.com/rktjmp/hotpot.nvim/blob/master/plugin/hotpot.vim#L9) command that works just like the built-in `:luafile`. This is very useful when hacking on a config that needs to be reloaded frequently.

**Comment by Olical** [comment]
So Conjure has `:ConjureEvalFile` which does this and it'd be easy to implement a similar thing for Aniseed, although I worry about feature creeping eval mechanics when Conjure is designed to solve all of those dynamic issues 🤔 

Like where do you print the output? How is it formatted? Just plain text echo? Conjure solves all of this nicely so I'm hesitant but not completely opposed. Maybe a barebones eval that just echos the result (even if that's not very easy to read / useful most of the time) just to give you _a_ tool.

**Comment by Olical** [comment]
Let me know what you think! I've pushed `:AniseedEval` and `AniseedEvalFile` to the `develop` branch. You can see docs on them with `:h AniseedEval` etc but they should be self explanatory.

**Comment by bandithedoge** [comment]
This looks like exactly what I meant

**Comment by Olical** [comment]
Cool! I'll let that sit in develop for a bit and release / tag it on master soon.
