### ISSUE TITLE
Can't require-macros, module not found

### ISSUE THREAD

**Issue by Liverm0r** [Olical/aniseed#112]
```bash
╰$ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```

Aniseed from master.  macros.fnl is copied to .confgi/nvim/lua/macros.fnl 

![image](https://user-images.githubusercontent.com/14236531/163548861-65078546-c472-47f0-9f87-b8d31ca199d5.png)

**Comment by Olical** [comment]
Can you not `require-macros [macros]`? I can't remember right now and I'll look deeper tomorrow but you shouldn't need the `fnl` prefix, maybe some old documentation told you to do that?

Also I would recommend moving your modules under a sub-directory so they're not directly under fnl/lua. That risks your file / module names colliding with other things at the top level, maybe it'll be fine, but I think it's good practice to have something like `fnl/dotfiles/my-code.fnl`.

**Comment by Liverm0r** [comment]
Yes, I guess the problem is in the fnl prefix, which I get from the docs. I renamed macros file from `macros.fnl` to `tmp-macros.fnl`,  but now I have 
<img width="847" alt="image" src="https://user-images.githubusercontent.com/14236531/163565367-1a557a02-eb09-4a74-afd8-9622ffd1312a.png">
This error with the macros from the tutorial __

**Comment by Liverm0r** [comment]
For example, if I announce the same macro with macro keyword, I can use it int the same module:
```fennel
(macro thrice-if [condition body]
  (fn step [i]
    (if (< i 3)
      (list (sym :if) condition (list (sym :do) body (step (+ 1 i))))))
  (step 0))
  ```

**Comment by Liverm0r** [comment]
I had a typo. So, everything words, if you provide path without `fnl.` prefix.
