### ISSUE TITLE
Unable to define multi-arity function

### ISSUE THREAD

**Issue by jimmyhogoboom** [Olical/aniseed#133]
I'm trying to evaluate this form:
```
(defn greeter
  ([] (greeter "Hello" "world"))
  ([target] (greeter "Hello" target))
  ([opener target] (println (str opener ", " target))))
```

The online REPL has no problem evaluating this. But Aniseed is returning an error, "expected parameters table": https://github.com/Olical/aniseed/blob/a7445c340fb7a0529f3c413eb99d3f8d29f50ba2/lua/aniseed/deps/fennel.lua#L1028

**Comment by Olical** [comment]
Hey. So is this in Clojure, I guess it is? And if so what keys are you
using to evaluate / where is your cursor at the time? There should be no
issues with evaluating this form, I can evaluate it just fine. I'd
recommend <prefix>er to evaluate the root form if you're not using that
already?

What does the log print when you evaluate this? It should log a snippet of
code that it sent to the REPL, it would be great to see that, it'll tell me
if something is being extracted wrong.

Do you have tree sitter installed and set up for Clojure? If so, have you
updated it recently?

**Comment by jimmyhogoboom** [comment]
Hi, thanks for the quick response!

I have tried <leader>er, along with visually highlighting the whole form and using <leader>E, and using <leader>Ea( while the cursor is on the first open paren.

Here's what the log prints when I ran <leader>er while the cursor is on the first 'd' of `defn`:
```
; --------------------------------------------------------------------------------
; eval (root-form): (defn greeter ([] (greeter "Hello" "wo...
; Compile error in unknown:1:?
;   expected parameters table
; 
; (defn greeter
; * Try adding function parameters as a list of identifiers in brackets.
```

I did just make sure treesitter is installed, and I tried running `:TSInstall clojure`, which seems to complete successfully, but I still get the same result.

**Comment by Olical** [comment]
That looks to me like the wrong filetype, Conjure thinks you're in a Fennel
buffer for some reason, not a Clojure buffer. Try :set filetype=clojure
then eval again.

**Comment by jimmyhogoboom** [comment]
Oh woof, ok this is more confusing than I thought, and I have misinformed you.

I am in a fnl file, so I guess I was wrong before, I'm writing Fennel, not Clojure? (Sorry, still new to this and not sure of the difference).

Unfortunately, when I try `:set filetype=clojure` or try this form in a `.clj` file, I get the erorr `No nREPL port file found` even after `:TSInstall clojure`. I think this is because I don't have Clojure installed on my system? I was hoping to learn just using Aniseed and Fennel in nvim.

**Comment by jimmyhogoboom** [comment]
Aha! Well that clears it up quite conclusively!
Thank you so much for your time helping me understand this! It's good to know I don't have some kind of uniquely broken environment 😅
