### ISSUE TITLE
Can we store generated lua files in a cache folder?

### ISSUE THREAD

**Issue by randomizedthinking** [Olical/aniseed#134]
This is a request, rather than an issue.

All the generated lua files are now in the configuration folder. Is it possible to store such files in a cache folder, such as ~/.local/share/nvim/cache/lua -- this way, all fnl files look like a first-class citizen for the nvim configuration?

**Comment by Olical** [comment]
Was going to be my recommendation too :) I'm almost certain that I provided
enough options to compile the Lua into any directory. Might take a bit of
doc reading and option fiddling, but should be possible!

**Comment by randomizedthinking** [comment]
Thanks, @bangedorrunt and @Olical. I will check the option out.
