### ISSUE TITLE
Unable to access some functions listed under `vim.fn`

### ISSUE THREAD

**Issue by yudistrange** [Olical/aniseed#145]
I'm trying to use the `wincmd` fn using aniseed in my neovim config.
But if I try evaluating it, I get the following error 

```
(vim.fn.wincmd "k")

; eval (current-form): (vim.fn.wincmd "k")
; Vim:E117: Unknown function: wincmd
```

But the function is there. I can see it being listed under `vim.fn` if I do the following.
```
(each [k v (pairs vim.fn)]
    (print k v))
```

I also tried evaluating the `vim.fn.winc` function. But that also results in the same error.

I tried evaluating other fns under `vim.fn` and they work as expected. For instance I can use `vim.fn.winnr`. 
Not sure if I'm missing on something very basic.

**Comment by Olical** [comment]
So to call wincmd, you'll need to use the nvim API for invoking ex
commands. I'm on my phone so I'm afraid I can't get a good example of that
right now but it's well documented.

**Comment by yudistrange** [comment]
Thanks @Olical for clarifying that.
It worked after I moved to `nvim.ex.wincmd`. Now I can finally wrap the navigation keys!
