### ISSUE TITLE
Request: More documentation on plugin development

### ISSUE THREAD

**Issue by lc9er** [Olical/aniseed#15]
This, perhaps, is not an Aniseed issue, but maybe my own lack of understanding of how to get plugins working. I've followed the guide so far, and things are working great. But I'm having a hard time getting from Aniseed & Conjure to nvim plugin. 

I'm able to get the functionality I wanted with my fnl file open, but even poking through your Fennel/Aniseed projects, I'm unable to figure out how to turn my functions into a working plugin. Is there any chance you can add some more documentation on this part of the process?

**Comment by Olical** [comment]
Yep, you're right that I need more docs, right now looking at my other examples like https://github.com/Olical/nvim-local-fennel and https://github.com/Olical/kkslider is probably a good way to work out how I do things. I hope?

**Comment by lc9er** [comment]
Yes. I'm just a raw newbie, fumbling my way through things. The kkslider seems like an especially good example, but I still failed to get it working. I'm sure if I keep mashing away at the keyboard, it'll work eventually, and I'll realize how easy it should have been in the first place!

**Comment by lc9er** [comment]
Found the answer in #12. It was a runtimepath issue - and my lack of understanding of the (n)vim plugin system. Simply placing my plugin directory under .config/nvim/plugged was insufficient. I used vim-plug to pull the project from my repo and it worked as expected. Sorry for the errant issue!

**Comment by Olical** [comment]
That's awesome, glad to hear it! And your issue is still a valid point, there needs to be more docs. I need to put time into it soon but I'm also hoping as more people try these things out they'll blog about there experiences and I can gather those up and share them.

Seeing others write about the pain points will help me know what to focus on in documentation too.
