### ISSUE TITLE
Syntax Highlighting for aniseed macros

### ISSUE THREAD

**Issue by tami5** [Olical/aniseed#16]
Hi there, so I cloned fennel.vim, and added syntax definition for macro and functions provide by aniseed. Is there a way to integrate those into aniseed repo, for better coding experience.

**Comment by Olical** [comment]
I think someone else also did this and there's a fork of fennel.vim, I just can't find it :thinking: I don't really know if you can augment a syntax highlight, maybe you can! Might need some googling to work out how to do that but you're more than welcome to pr them into this repo, probably under `syntax/aniseed.vim`? At a guess?

**Comment by tami5** [comment]
Sure I'll do that and we can further collaborate. I'll create pr soon.

Thanks

**Comment by tami5** [comment]
I think with tree-setter no need to define special syntax options
