### ISSUE TITLE
Question: what about the runtime directories?

### ISSUE THREAD

**Issue by psunanand** [Olical/aniseed#18]
First off, I would like to say thanks so much for your plugin. It gives me such a huge motivation to learn more about clojure for my favorite nvim. 

However, I was wondering how you would  integrate aniseed with e.g. those type specific configurations in after/ftplugin or some user custom defined functions in autoload/ . I know for a fact that I can leave those files in VimScript as they are, and the rest in Clojure as you showed on your blog post. But I feel like it would be cool if I can write all those files in Clojure too. 

Since I'm pretty new to clojure and lua, please let me know if I misunderstand how aniseed works.

**Comment by tami5** [comment]
Hay, basically aniseed and fennel is built on top of lua support and currently as far as I know these stuff is not supported in lua. If you want to use a function you defined in fennel with aniseed you need to to require it like `lua require('dotfiles.mymodule').function()

For me defining ft specific configurations, I use autocmds. In the future it would be possible to have fnl/lua files in after ot ftplugin as the core team in lua are trying to increase the support of lua.

Hope this shade some light.

**Comment by psunanand** [comment]
@tami5 I agree with you that all the filetype specifics could be written using autocmds and not necessarily needed to be put in e.g. after/ftplugin. But I really like the inherent structure of vim runtime directories. Anyway because I have to learn using clojure, I might try rewriting in clojure. Do you have any recommendation for the file structures ?

**Comment by tami5** [comment]
Funny you would ask, I'm currently working on re configuring my neovim in lua, (totally applicable to fnl) and here's my repo https://github.com/tami5/nvim, as of now it contains a simple outline.

**Comment by psunanand** [comment]
Interesting. Because I plan to use clojure in the future, I will try to do the same but in clojure

**Comment by psunanand** [comment]
I will close this one since I guess it shouldn't be a problem of this side. Anyway thanks so much for your great plugin
