### ISSUE TITLE
Add force option to aniseed.env.init that forces compile

### ISSUE THREAD

**Issue by BerkeleyTrue** [Olical/aniseed#27]
I've had this issue several times now were I'm making changes to macros and I'm trying to re-compile my whole project so I can see the result. 

There is a check to see if the last modified timestamp has changed which prevents compilation of files when no changes have happened, which means I either need to blow away the lua file, or add useless comments to change timestamps.

I've got a branch of aniseed that allows me to pass force to compile the code while I'm editing for those cases where REPL won't due. Is this something you'd be ok with in the this project?

i.e.
```lua
lua require("aniseed.env").init({ force = true })
```

**Comment by Olical** [comment]
Ah this is already an option! Did I not document it :thinking: or did it not work for you? The options you pass flow through until they reach `compile.file`: https://github.com/Olical/aniseed/blob/b9cb8a2451623f6455e6e029259f37c8952c5bce/fnl/aniseed/compile.fnl#L30

Which takes a `force` key already which skips those modified checks.

**Comment by BerkeleyTrue** [comment]
The options don't get pass through env.init don't get passed to compile.glob

https://github.com/Olical/aniseed/blob/b9cb8a2451/fnl/aniseed/env.fnl#L16

**Comment by Olical** [comment]
Oh no! That should be the case, my bad. So yeah, I'm totally open to passing the opt through these layers into compile.file.

**Comment by BerkeleyTrue** [comment]
closed with #28
