### ISSUE TITLE
Change aniseed.env (Fennel dotfiles) to use an option instead of a function call

### ISSUE THREAD

**Issue by Olical** [Olical/aniseed#31]
People that want to use Aniseed's "Neovim configuration as Fennel" tooling need to call an Aniseed function to kick start the process, this can lead to issues if Aniseed isn't loaded yet which can happen with newer package management methods.

I propose replacing this function call with an option that you set instead. If you set the option Aniseed will call the required function on your behalf when it's `plugin/aniseed.vim` script is loaded. I _think_ this is easier for people to use and works around a bunch of issues!

The old method will still exist, this will just be the canonical documented path to it.

**Comment by Olical** [comment]
Done! Pretty sure.

**Comment by mhanberg** [comment]
Just tried this out, seems to work for me! Thanks!
