### ISSUE TITLE
Add a "blessed" way of getting the plugin directory as well as the paths to induvidual source files

### ISSUE THREAD

**Issue by Olical** [Olical/aniseed#34]
jlesquembre on Discord asked about this and I think it'd be a great much needed feature! Not sure how to do this yet, so needs some hammock time / RnD.

**Comment by Olical** [comment]
Added `*file*` to all module on `develop` which is a relative path to the original `.fnl` file that was used to compile that output. So even in pure Lua output you can tell where the code came from.

**Comment by jlesquembre** [comment]
thanks @Olical !

**Comment by Olical** [comment]
I don't think this fully answered the original request but I can revisit it
🤔 just wanted to get SOME file info in there for now
