### ISSUE TITLE
<Enhancement> Include the Fennel.vim fork mentioned in Conjure

### ISSUE THREAD

**Issue by enderger** [Olical/aniseed#35]
As of the latest [Conjure](https://github.com/Olical/conjure) release, there was a mention of possibly including your [Fennel.vim](https://github.com/Olical/fennel.vim) fork in the Conjure+Aniseed toolkit. I personally think that this makes sense to include in this project, as without it Aniseed is not quite as useful. It only really makes sense to use with Fennel syntax highlighting, and probably should be included here.

**Comment by Olical** [comment]
Done 😄 you still can't get away with just Conjure, so you'll need Aniseed and Conjure if you want to work on Fennel and have syntax, but still. If you're using Aniseed you don't need a syntax plugin (on the develop branch / when I release)
