### ISSUE TITLE
"aniseed.macros module not found" on v3.16.0

### ISSUE THREAD

**Issue by Grazfather** [Olical/aniseed#70]
I saw #25, but I am using new neovim and new aniseed.

Trying to bisect, I get different errors. On master I get the above.

On v3.15.0 I get

```
line    5:
E735: Can only compare Dictionary with Dictionary
E116: Invalid arguments for function luaeval
```

On v3.16.0 I get
```
  aniseed.macros module not found.
# AND
module 'aniseed.autoload' not found
```

Everything seems to work fine on v3.14.0.

```
:version
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-sqSnmX/neovim-0.6.0~ubuntu1+git202109241202-433bda405-adeb5640f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wcon
version -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-sqSnmX/neovim-0.6.0~ubuntu1+git202109241202-433bda405-adeb5640f/build/config -I/build/neovim-sqSnmX/neovim-0
.6.0~ubuntu1+git202109241202-433bda405-adeb5640f/src -I/build/neovim-sqSnmX/neovim-0.6.0~ubuntu1+git202109241202-433bda405-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-sqSnmX/neovim-0.6.0~ubuntu1+git202109241202-433bda405-adeb5640f/build/src/nvim/auto -I/build/neovim-sqSnmX/neovim-0.6.0~ubuntu1+git202109241202-433bda405-adeb5640f/build/include
Compiled by buildd@lgw01-amd64-028

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by babygau** [comment]
@Grazfather switch to develop branch will fix this issue.

**Comment by Olical** [comment]
@babygau is most likely correct, I'm on the verge of releasing a large batch of improvements and Lua file size reductions. Please let me know if `develop` doesn't help! I'll dig into it and try to reproduce it if so.

**Comment by Grazfather** [comment]
Develop (bb332fc) seems to work, though strangely the new fennel complained about me having `<leader>:` as a symbol name.

**Comment by Olical** [comment]
Ah interesting! Well I'm glad the main bug is fixed but yeah, that'll probably be something changed in the Fennel compiler itself. They're making quite a few changes at the moment in the run up to v1, so I think any remaining breaking changes will come through soon before things stabilise for v1+.

I'm not sure what to suggest with that, they may have just changed the symbol rules but that does seem like an odd one... I don't see why that wouldn't be allowed unless `:` is a special character now?

**Comment by Olical** [comment]
Ohh neat! So I think the main solution right now is for me to release all
my current weeks of work 😬 I just need a few people to smoke test with
their config etc while I use it at work to confirm there's no major
outstanding issues. I changed a LOT of internals.

**Comment by Grazfather** [comment]
That would be nice. Happy to help test.

Also a note that I didn't see this error with Neovim from brew, but only Neovim from the unstable ubuntu PPA.

**Comment by Olical** [comment]
Should be fixed now, released!

**Comment by Grazfather** [comment]
Confirmed that new versions pushed (3.17.0 to 3.22.0) all seem to work well.
