### ISSUE TITLE
Destructuring  support in module macro

### ISSUE THREAD

**Issue by babygau** [Olical/aniseed#76]
I'm wondering if it's possible to have sth like

```
(module xyz
    {autoload {{: foo} baz}})
```

**Comment by Olical** [comment]
Implemented! It was a two line change, it used to need a LOT more work but then I rewrote all of the module macro system things which made it easy and I didn't realise. I think everything is working fine and it _just works_?

**Comment by Olical** [comment]
Well, everything seems fine in Aniseed but I'm seeing errors when compiling Conjure with this... so maybe not perfect yet!

**Comment by Olical** [comment]
Fixed!
