### ISSUE TITLE
make test fails, even on initial project creation

### ISSUE THREAD

**Issue by raymond-w-ko** [Olical/aniseed#80]
Hello, am I missing something?

I tried creating a project with `seed.sh`, and immediately am getting:
```
Error detected while processing command line:
E5108: Error executing lua ...nvim/site/pack/packer/start/aniseed/lua/aniseed/core.lua:125: module 'nvim-project.main-test' not found:
```

I'm looking at the scripts and it seems like it can't find the compiled test from the example, even though `runtimepath` is being set correctly. Am I the only one getting this?

**Comment by raymond-w-ko** [comment]
Is this related to me using the latest neovim builds from Git and not a stable version (v0.6.0-dev)?

**Comment by raymond-w-ko** [comment]
If I comment out `rm -rf test/lua` in the `test` target, then it works the second time. Is this something like files not existing at startup means it will never exist to the `rtp` loader?

**Comment by raymond-w-ko** [comment]
Another related bug concerning macros: I had to take out `rm -rf lua` in the `compile` Makefile target, or nvim does not see the output lua directory, and therefore cannot find the path to the copied over macros.fnl file.

```
E5108: Error executing lua ...m/site/pack/packer/start/aniseed/lua/aniseed/compile.lua:72: Could not open file: lua/nvim-project/macros.fnl
```

**Comment by Olical** [comment]
Hey sorry for the delay, I'm not sure what's going on here right now. It _could_ be your Neovim version since they've been making a few breaking changes around plugin / Lua paths recently 😭 the best way to confirm that would be to launch it with stable Neovim and see if that works okay.

The only other thing I can think of is OS / path / dir name related issues. Like if you ran `seed.sh` in a directory with a name that I hadn't anticipated, with characters something didn't like...

I've personally never seen this and I can't reproduce it using the same project name (`nvim-project`). I can't easily try Neovim 0.6 since I'm on NixOS, I'd need to go fiddling with .nix files that I'm not hugely comfortable with 😅 

Although maybe by this point you're not trying to use this project anymore 😬

**Comment by raymond-w-ko** [comment]
I am currently still using this project: https://github.com/raymond-w-ko/nvim-sexp-edit
Basically I am trying to (re)write something similar to: https://github.com/guns/vim-sexp but in Fennel+Lua
Right now I am in the process of still learning about Fennel and thinking over how I want to approach things, but have been side tracked with video games 😅.

I just removed all the lines with `rm` in the Makefile, and it everything works fine so far.

I'm going with the theory that between your stable version and the latest in Git, something changed so if a directory doesn't exists on nvim startup or first Lua usage, then it never considers that it can get created without neovim restarting. Like a missing cache invalidation issue.

I'll revisit this when neovim 0.6 hits release candidate or is released.

**Comment by Olical** [comment]
I _think_ I fixed this just now! It looks like Neovim 0.6 removed a feature that copied runtimepath items into the package.path, which I relied on. The `:h lua` docs say it still does this copying mechanic but I can't see it doing it any more, I've worked around this problem so hopefully it's fine now.

**Comment by katawful** [comment]
I'm experiencing this on my end still, with NeoVim 0.6, while working on a repo that uses Aniseed. I can't build when I include the tests. Removing the `rm -rf` lines succeeds however. This is with a current commit (through the Aniseed dependency scripts)

**Comment by Olical** [comment]
Ah I hadn't released, the change was made to the develop branch. Releasing the update now that fixed runtimepath stuff on Neovim 0.6 for me.

**Comment by Olical** [comment]
I still can't reproduce this 🤔 I just created a fresh seeded project and it worked fine. I'm guessing you would still run into this issue though...

**Comment by raymond-w-ko** [comment]
With the latest neovim and/or aniseed everything works for me now, so I am closing this now.
