### ISSUE TITLE
aniseed.nvim.nvim_buf_set_keymap missing?

### ISSUE THREAD

**Issue by zbouslikhin** [Olical/aniseed#86]
I'm currently trying to configure an nvim plugin that involves using the function `nvim_buf_set_keymap`.
Using aniseed, I'm exporting nvim to use that function. However, it looks like the function does not exist (returns "attempt to call field nvim_buf_set_keymap (a nil value)".
The code is looking like this:
```fnl
(module config.plugin.toggletermPref
  {autoload 
   {toggletermPref toggleterm
    nvim aniseed.nvim}})

(local opts {:noremap true})	
(nvim.nvim_buf_set_keymap 0 :t :<esc> "<C-\\><C-n>" opts)
```
![image](https://user-images.githubusercontent.com/47977073/145683025-c4ea5dd5-c0a2-4710-a569-57c60011b86c.png)

**Comment by Olical** [comment]
I think that's just nvim.buf_set_keymap, it's like the nvim prefix is dropped over the entire API when using that nvim wrapper module.

**Comment by Olical** [comment]
Closing since this is a docs issue more than anything. It's `nvim.buf_set_keymap`, not `nvim.nvim_buf_set_keymap`
