### ISSUE TITLE
Lua interaction with new module macro breaks

### ISSUE THREAD

**Issue by katawful** [Olical/aniseed#98]
Now that modules always return the module, some Lua interactions break. A Lualine theme built with Aniseed (useful for adjusting colors from a colorscheme built with Aniseed) will now no longer be able to load themes. These plugins expect a file with a table of the colors returned from the file found (i.e. `lua/lualine/themes/theme-name.lua` for lualine)

While the new method is generally really helpful, it leaves me unable to interact with Lua properly when using Aniseed

**Comment by Olical** [comment]
It may not be ideal, I need to think of a better solution, but you could
use (def X "y") to ensure a table is returned containing a key X and a
value y. Not ideal really though, I'll have to think of a way to let people
return tables and bypass the module system.

**Comment by Olical** [comment]
https://github.com/katawful/kat.nvim/issues/7#issuecomment-1069595738

Linking here too since I explained within @katawful's project issue too.
